Hotel card
samuelfcf/drivent-back pull request #6
Opened 2022-01-21 16:42 UTC by Bruno-Kohn

2022-01-21 17:13 UTC, Deltinha requested changes

2022-01-21 17:13 UTC, Deltinha commented on src/controllers/client/hotel.ts
> +}
essa função finaliza sem salvar a reserva

2022-01-21 17:13 UTC, Deltinha commented on src/entities/Enrollment.ts
> +  @Column()
tem que setar aqui pra permitir NULLS. Pq o formulário inicial não seta valor pra room

2022-01-22 00:13 UTC, Deltinha approved these changes

2022-01-22 17:48 UTC, lfelipelizeu requested changes

2022-01-22 17:48 UTC, lfelipelizeu commented on src/entities/User.ts
> +  //address: Address;
Essa linha é pra estar comentada mesmo?

2022-01-22 17:48 UTC, lfelipelizeu commented on src/services/client/hotel.ts
> +  await Enrollment.saveNewBooking(userId, roomId);
Acho que tá faltando o return do if aqui, porque desse jeito acredito que quando tivesse uma anterior ele ia salvar dentro do if e depois salvar na função fora.

2022-01-22 22:35 UTC, Bruno-Kohn commented on src/entities/User.ts
> +  //address: Address;
Essa relacao nao faz sentido, por isso comentei

2022-01-23 01:30 UTC, Deltinha approved these changes

2022-01-23 01:30 UTC, Deltinha commented on src/entities/Enrollment.ts
> +  @OneToOne(() => Address, (address) => address.enrollment)
Por que esse eager foi removido? Ele tá dando problema do outro lado?

2022-01-23 17:49 UTC, Deltinha commented on src/entities/User.ts
> +  //address: Address;
Realmente, ele tá pegando o address e colocando em enrollment

2022-01-24 02:13 UTC, Deltinha approved these changes

2022-01-24 02:31 UTC, samuelfcf approved these changes

2022-01-24 02:50 UTC, lfelipelizeu approved these changes

2022-01-24 15:30 UTC, merged